{
 "title": "SNSKY Pool",
 "description": "SNSKY Pool Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 } },
  {
   "title": "Pool Performance",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(cardano_node_metrics_Forge_node_not_leader_int{alias=\"block-producer-node\"} / cardano_node_metrics_Forge_forge_about_to_lead_int{alias=\"block-producer-node\"} * 100)",
     "legendFormat": "{{none}}"
    }
   ]
  },
  {
   "title": "KES Key Rotation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_currentKESPeriod_int",
     "legendFormat": "Current Period"
    },
    {
     "expr": "cardano_node_metrics_operationalCertificateExpiryKESPeriod_int",
     "legendFormat": "Expiry Period"
    }
   ]
  },
  {
   "title": "KES Key : Days Left",
   "type": "gauge",
   "description": "Remaining KES DAYS before we need to rotate keys",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(cardano_node_metrics_remainingKESPeriods_int * 1.5)",
     "legendFormat": "{{none}}"
    }
   ]
  },
  {
   "title": "Current Epoch Progress",
   "type": "gauge",
   "description": "Slot height in current epoch (taken from Core node)",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotInEpoch_int{alias=\"block-producer-node\"}/432000 ",
     "legendFormat": "{{none}}"
    }
   ]
  },
  {
   "title": "Epoch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_epoch_int{instance=\"localhost:12798\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Active Stake",
   "type": "stat",
   "description": "in ADA",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "adapools_active_stake{alias=\"relaynode1\"}/1000000000"
    }
   ]
  },
  {
   "title": "Core Node System Health",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 7, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\",alias=\"block-producer-node\"}[1m])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"block-producer-node\"} / (node_memory_MemTotal_bytes{alias=\"block-producer-node\"})))* 100",
     "legendFormat": "RAM"
    },
    { "expr": "0", "legendFormat": "SWAP" },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"block-producer-node\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"block-producer-node\"})",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "title": "Peers (Core)",
   "type": "stat",
   "description": "Connected peers to/from Core Node",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_connectedPeers_int{alias=\"block-producer-node\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Core TX's processed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int{alias=\"block-producer-node\"}",
     "legendFormat": "Core"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Core node uptime",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rts_gc_wall_ms{alias=\"block-producer-node\"} / (1000)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Live Stake",
   "type": "stat",
   "description": "in ADA",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "adapools_total_stake{alias=\"relaynode1\"}/1000000000"
    }
   ]
  },
  {
   "title": "Blocks Forged",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "blocks_lifetime{alias=\"relay2\"} + blocks_epoch{alias=\"relay2\"}"
    }
   ]
  },
  {
   "title": "Pledged (ADA)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "adapools_pledge{alias=\"relaynode1\"}/1000000",
     "legendFormat": "ADA"
    }
   ]
  },
  {
   "title": "Blocks Assigned",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_forge_about_to_lead_int{alias=\"block-producer-node\"} - cardano_node_metrics_Forge_node_not_leader_int{alias=\"block-producer-node\"}"
    }
   ]
  },
  {
   "title": "Relay Node System Health",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\",alias=\"relaynode1\"}[1m])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"relaynode1\"} / (node_memory_MemTotal_bytes{alias=\"relaynode1\"})))* 100",
     "legendFormat": "RAM"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes{alias=\"relaynode1\"} / node_memory_SwapTotal_bytes{alias=\"relaynode1\"})) * 100",
     "legendFormat": "SWAP"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"relaynode1\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"relaynode1\"})",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "title": "Peers (Relay)",
   "type": "stat",
   "description": "Connected peers to/from Relay 1",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_connectedPeers_int{alias=\"relaynode1\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Relay TX's processed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int{alias=\"relaynode1\"}",
     "legendFormat": "Relay"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Relay node 1 uptime",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rts_gc_wall_ms{alias=\"relaynode1\"} / (1000)"
    }
   ]
  },
  {
   "title": "Delegators",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "adapools_delegators{alias=\"relaynode1\"}"
    }
   ]
  },
  {
   "title": "Pool Rank",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "adapools_rank{alias=\"relaynode1\"}"
    }
   ]
  },
  {
   "title": "Chain Density",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_density_real{alias=\"block-producer-node\"} * 100",
     "legendFormat": "Core"
    },
    {
     "expr": "cardano_node_metrics_density_real{alias=\"relaynode1\"} * 100",
     "legendFormat": "Relay"
    }
   ]
  },
  {
   "title": "Block height",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_blockNum_int{alias=\"block-producer-node\"}",
     "legendFormat": "Core"
    },
    {
     "expr": "cardano_node_metrics_blockNum_int{alias=\"relaynode1\"}",
     "legendFormat": "Relay"
    }
   ]
  },
  {
   "title": "Slot Height",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_slotNum_int{alias=\"block-producer-node\"}",
     "legendFormat": "Core"
    },
    {
     "expr": "cardano_node_metrics_slotNum_int{alias=\"relaynode1\"}",
     "legendFormat": "Relay"
    }
   ]
  },
  {
   "title": "System Load (Core Node)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "yaxes": [
    { "format": "%", "label": "Load" }
   ],
   "targets": [
    {
     "expr": "node_load1{alias=\"block-producer-node\"}*100",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{alias=\"block-producer-node\"}*100",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{alias=\"block-producer-node\"}*100",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "System Load (Relay Node)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "yaxes": [
    { "format": "%", "label": "Load" }
   ],
   "targets": [
    {
     "expr": "node_load1{alias=\"relaynode1\"}*100",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{alias=\"relaynode1\"}*100",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{alias=\"relaynode1\"}*100",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "Connected Peers ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_connectedPeers_int{alias=\"block-producer-node\"}",
     "legendFormat": "Core"
    },
    {
     "expr": "cardano_node_metrics_connectedPeers_int{alias=\"relaynode1\"}",
     "legendFormat": "Relay"
    }
   ]
  },
  {
   "title": "Block Sync Speed (blocks / min)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate (cardano_node_metrics_blockNum_int{alias=\"block-producer-node\"}[150s]) *60",
     "legendFormat": "Core"
    },
    {
     "expr": "rate (cardano_node_metrics_blockNum_int{alias=\"relaynode1\"}[150s]) *60",
     "legendFormat": "Relay"
    }
   ]
  },
  {
   "title": "Time Synchronization (Core Node)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "node_timex_estimated_error_seconds{alias=\"block-producer-node\"}",
     "legendFormat": "Est. error(s)"
    },
    {
     "expr": "node_timex_offset_seconds{alias=\"block-producer-node\"}",
     "legendFormat": "Offset: Node vs. Ref."
    },
    {
     "expr": "node_timex_maxerror_seconds{alias=\"block-producer-node\"}",
     "legendFormat": "Max. Error (s)"
    }
   ]
  },
  {
   "title": "Time Synchronization (Relay Node)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "node_timex_estimated_error_seconds{alias=\"relaynode1\"}",
     "legendFormat": "Est. error(s)"
    },
    {
     "expr": "node_timex_offset_seconds{alias=\"relaynode1\"}",
     "legendFormat": "Offset: Node vs. Ref."
    },
    {
     "expr": "node_timex_maxerror_seconds{alias=\"relaynode1\"}",
     "legendFormat": "Max. Error (s)"
    }
   ]
  },
  {
   "title": "Memory Utilization ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"block-producer-node\"} / (node_memory_MemTotal_bytes{alias=\"block-producer-node\"})))* 100",
     "legendFormat": "Core"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"relaynode1\"} / (node_memory_MemTotal_bytes{alias=\"relaynode1\"})))* 100",
     "legendFormat": "Relay"
    }
   ]
  },
  {
   "title": "Peak Memory Allocated",
   "type": "graph",
   "description": "Counts only memory that is physically free (from OS, in MBytes)",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "rts_gc_peak_megabytes_allocated{alias=\"block-producer-node\"}",
     "legendFormat": "Core"
    },
    {
     "expr": "rts_gc_peak_megabytes_allocated{alias=\"relaynode1\"}",
     "legendFormat": "Relay"
    }
   ]
  },
  {
   "title": "Mempool Transactions",
   "type": "graph",
   "description": "current",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "tx" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_txsInMempool_int{alias=\"block-producer-node\"}",
     "legendFormat": "Core"
    },
    {
     "expr": "cardano_node_metrics_txsInMempool_int{alias=\"relaynode1\"}",
     "legendFormat": "Relay"
    }
   ]
  },
  {
   "title": "Current \"Residency\" (amount of live data)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "rts_gc_current_bytes_used{alias=\"block-producer-node\"}/(1024*1024)",
     "legendFormat": "Core"
    },
    {
     "expr": "rts_gc_current_bytes_used{alias=\"relaynode1\"}/(1024*1024)",
     "legendFormat": "Relay"
    }
   ]
  },
  {
   "title": "Aggregate Data Transfer",
   "type": "graph",
   "description": "1 hour rolling window",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias=\"block-producer-node\"}[1h])) * 3600",
     "legendFormat": "Core"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias=\"relaynode1\"}[1h])) * 3600",
     "legendFormat": "Relay"
    }
   ]
  },
  {
   "title": "Max \"Residency\"",
   "type": "graph",
   "description": "Amount of live data, MBytes",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "rts_gc_max_bytes_used{alias=\"block-producer-node\"} /(1024*1024)",
     "legendFormat": "Core"
    },
    {
     "expr": "rts_gc_max_bytes_used{alias=\"relaynode1\"} /(1024*1024)",
     "legendFormat": "Relay"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{alias=\"block-producer-node\"}",
     "legendFormat": "Core"
    },
    {
     "expr": "node_filefd_allocated{alias=\"relaynode1\"}",
     "legendFormat": "Relay"
    }
   ]
  },
  {
   "title": "RSS (allocated memory in RAM)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "(cardano_node_metrics_Mem_resident_int{alias=\"block-producer-node\"}*4096)/(1024*1024)",
     "legendFormat": "Core"
    },
    {
     "expr": "(cardano_node_metrics_Mem_resident_int{alias=\"relaynode1\"}*4096)/(1024*1024)",
     "legendFormat": "Relay"
    }
   ]
  }
 ]
}