{
 "title": "SNSKY Pool",
 "description": "SNSKY Pool Monitor",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 } },
  {
   "title": "KES Key Rotation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_currentKESPeriod_int",
     "legendFormat": "Current Period"
    },
    {
     "expr": "cardano_node_metrics_operationalCertificateExpiryKESPeriod_int",
     "legendFormat": "Expiry Period"
    }
   ]
  },
  {
   "title": "KES Key : Days Left",
   "type": "gauge",
   "description": "Remaining KES DAYS before we need to rotate keys",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(cardano_node_metrics_remainingKESPeriods_int * 1.5)",
     "legendFormat": "{{none}}"
    }
   ]
  },
  {
   "title": "Pool Performance",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(cardano_node_metrics_Forge_node_not_leader_int{alias=\"block-producer-node\"} + cardano_node_metrics_Forge_adopted_int{alias=\"block-producer-node\"}) / cardano_node_metrics_Forge_forge_about_to_lead_int{alias=\"block-producer-node\"} * 100",
     "legendFormat": "{{none}}"
    }
   ]
  },
  {
   "title": "Current Epoch Progress",
   "type": "gauge",
   "description": "Slot height in current epoch (taken from Core node)",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotInEpoch_int{alias=\"block-producer-node\"}/432000 ",
     "legendFormat": "{{none}}"
    }
   ]
  },
  {
   "title": "Epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_epoch_int{alias=\"block-producer-node\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Pledged",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "cexplorer_pledge/1000000" }
   ]
  },
  {
   "title": "Leader Slots",
   "type": "stat",
   "description": "Next Epoch",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "snsky_metrics_leaderSlots", "legendFormat": "Leader Slots" }
   ]
  },
  {
   "title": "Core Node System Health",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\",alias=\"block-producer-node\"}[1m])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"block-producer-node\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"block-producer-node\"})",
     "legendFormat": "Disk"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"block-producer-node\"} / (node_memory_MemTotal_bytes{alias=\"block-producer-node\"})))* 100",
     "legendFormat": "RAM"
    },
    {
     "expr": "(1- (node_memory_SwapFree_bytes{alias=\"block-producer-node\"} / node_memory_SwapTotal_bytes{alias=\"block-producer-node\"})) * 100",
     "legendFormat": "SWAP"
    }
   ]
  },
  {
   "title": "Peers (Core)",
   "type": "stat",
   "description": "Connected peers to/from Core Node",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_connectedPeers_int{alias=\"block-producer-node\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Core TX's processed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int{alias=\"block-producer-node\"}",
     "legendFormat": "Core"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Core node uptime",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rts_gc_wall_ms{alias=\"block-producer-node\"} / (1000)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Activestake",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(cexplorer_stake_active/10000000)"
    }
   ]
  },
  {
   "title": "Blocks Epoch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "cexplorer_blocks_epoch" }
   ]
  },
  {
   "title": "Relay Node System Health",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\",alias=\"relaynode1\"}[1m])) * 100)",
     "legendFormat": "CPU R1"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"relaynode1\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"relaynode1\"})",
     "legendFormat": "Disk R1"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"relaynode1\"} / (node_memory_MemTotal_bytes{alias=\"relaynode1\"})))* 100",
     "legendFormat": "RAM R1"
    },
    { "expr": "0", "legendFormat": "SWAP R1" },
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\",alias=\"relaynode2\"}[1m])) * 100)",
     "legendFormat": "CPU R2"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"relaynode2\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"relaynode2\"})",
     "legendFormat": "Disk R2"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"relaynode2\"} / (node_memory_MemTotal_bytes{alias=\"relaynode2\"})))* 100",
     "legendFormat": "RAM R2"
    },
    { "expr": "0", "legendFormat": "SWAP R2" },
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\",alias=\"relaynode3\"}[1m])) * 100)",
     "legendFormat": "CPU R3"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"relaynode3\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"relaynode3\"})",
     "legendFormat": "Disk R3"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"relaynode3\"} / (node_memory_MemTotal_bytes{alias=\"relaynode3\"})))* 100",
     "legendFormat": "RAM R3"
    },
    {
     "expr": "(1- (node_memory_SwapFree_bytes{alias=\"relaynode3\"} / node_memory_SwapTotal_bytes{alias=\"relaynode3\"})) * 100",
     "legendFormat": "SWAP"
    },
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\",alias=\"relaynode4\"}[1m])) * 100)",
     "legendFormat": "CPU R4"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"relaynode4\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"relaynode4\"})",
     "legendFormat": "Disk R4"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"relaynode4\"} / (node_memory_MemTotal_bytes{alias=\"relaynode4\"})))* 100",
     "legendFormat": "RAM R4"
    },
    {
     "expr": "(1- (node_memory_SwapFree_bytes{alias=\"relaynode4\"} / node_memory_SwapTotal_bytes{alias=\"relaynode4\"})) * 100",
     "legendFormat": "SWAP R4"
    }
   ]
  },
  {
   "title": "Peers (Relay)",
   "type": "stat",
   "description": "Connected peers to/from Relay 1",
   "gridPos": { "h": 8, "w": 3, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_connectedPeers_int{alias=\"relaynode1\"}",
     "legendFormat": "Relay1"
    },
    {
     "expr": "cardano_node_metrics_connectedPeers_int{alias=\"relaynode2\"}",
     "legendFormat": "Relay2"
    },
    {
     "expr": "cardano_node_metrics_connectedPeers_int{alias=\"relaynode3\"}",
     "legendFormat": "Relay3"
    },
    {
     "expr": "cardano_node_metrics_connectedPeers_int{alias=\"relaynode4\"}",
     "legendFormat": "Relay4"
    }
   ]
  },
  {
   "title": "Relay TX's processed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int{alias=\"relaynode1\"}",
     "legendFormat": "Relay1"
    },
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int{alias=\"relaynode2\"}",
     "legendFormat": "Relay2"
    },
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int{alias=\"relaynode3\"}",
     "legendFormat": "Relay3"
    },
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int{alias=\"relaynode4\"}",
     "legendFormat": "Relay4"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Relay node 1 uptime",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rts_gc_wall_ms{alias=\"relaynode1\"} / (1000)",
     "legendFormat": "Relay1"
    },
    {
     "expr": "rts_gc_wall_ms{alias=\"relaynode2\"} / (1000)",
     "legendFormat": "Relay2"
    },
    {
     "expr": "rts_gc_wall_ms{alias=\"relaynode3\"} / (1000)",
     "legendFormat": "Relay3"
    },
    {
     "expr": "rts_gc_wall_ms{alias=\"relaynode4\"} / (1000)",
     "legendFormat": "Relay4"
    }
   ]
  },
  {
   "title": "Delegators",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "cexplorer_delegators" }
   ]
  },
  {
   "title": "Blocks Minted",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "cexplorer_blocks_lifetime" }
   ]
  },
  {
   "title": "Rewards",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "cexplorer_roa_lifetime" }
   ]
  },
  {
   "title": "PoolRank",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "cexplorer_position" }
   ]
  },
  {
   "title": "Chain Density",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_density_real{alias=\"block-producer-node\"} * 100",
     "legendFormat": "Core"
    },
    {
     "expr": "cardano_node_metrics_density_real{alias=\"relaynode1\"} * 100",
     "legendFormat": "Relay1"
    },
    {
     "expr": "cardano_node_metrics_density_real{alias=\"relaynode2\"} * 100",
     "legendFormat": "Relay2"
    },
    {
     "expr": "cardano_node_metrics_density_real{alias=\"relaynode3\"} * 100",
     "legendFormat": "Relay3"
    },
    {
     "expr": "cardano_node_metrics_density_real{alias=\"relaynode4\"} * 100",
     "legendFormat": "Relay4"
    }
   ]
  },
  {
   "title": "Block height",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_blockNum_int{alias=\"block-producer-node\"}",
     "legendFormat": "Core"
    },
    {
     "expr": "cardano_node_metrics_blockNum_int{alias=\"relaynode1\"}",
     "legendFormat": "Relay1"
    },
    {
     "expr": "cardano_node_metrics_blockNum_int{alias=\"relaynode2\"}",
     "legendFormat": "Relay2"
    },
    {
     "expr": "cardano_node_metrics_blockNum_int{alias=\"relaynode3\"}",
     "legendFormat": "Relay3"
    },
    {
     "expr": "cardano_node_metrics_blockNum_int{alias=\"relaynode4\"}",
     "legendFormat": "Relay4"
    }
   ]
  },
  {
   "title": "Slot Height",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_slotNum_int{alias=\"block-producer-node\"}",
     "legendFormat": "Core"
    },
    {
     "expr": "cardano_node_metrics_slotNum_int{alias=\"relaynode1\"}",
     "legendFormat": "Relay1"
    },
    {
     "expr": "cardano_node_metrics_slotNum_int{alias=\"relaynode2\"}",
     "legendFormat": "Relay2"
    },
    {
     "expr": "cardano_node_metrics_slotNum_int{alias=\"relaynode3\"}",
     "legendFormat": "Relay3"
    },
    {
     "expr": "cardano_node_metrics_slotNum_int{alias=\"relaynode4\"}",
     "legendFormat": "Relay4"
    }
   ]
  },
  {
   "title": "System Load (Core Node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "yaxes": [
    { "format": "%", "label": "Load" }
   ],
   "targets": [
    {
     "expr": "node_load1{alias=\"block-producer-node\"}*100",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{alias=\"block-producer-node\"}*100",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{alias=\"block-producer-node\"}*100",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "System Load (Relay Node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "yaxes": [
    { "format": "%", "label": "Load" }
   ],
   "targets": [
    {
     "expr": "node_load1{alias=\"relaynode1\"}*100",
     "legendFormat": "R1 Load 1m"
    },
    {
     "expr": "node_load5{alias=\"relaynode1\"}*100",
     "legendFormat": "R1 Load 5m"
    },
    {
     "expr": "node_load15{alias=\"relaynode1\"}*100",
     "legendFormat": "R1 Load 15m"
    },
    {
     "expr": "node_load1{alias=\"relaynode2\"}*100",
     "legendFormat": "R2 Load 1m"
    },
    {
     "expr": "node_load5{alias=\"relaynode2\"}*100",
     "legendFormat": "R2 Load 5m"
    },
    {
     "expr": "node_load15{alias=\"relaynode2\"}*100",
     "legendFormat": "R2 Load 15m"
    },
    {
     "expr": "node_load1{alias=\"relaynode3\"}*100",
     "legendFormat": "R3 Load 1m"
    },
    {
     "expr": "node_load5{alias=\"relaynode3\"}*100",
     "legendFormat": "R3 Load 5m"
    },
    {
     "expr": "node_load15{alias=\"relaynode3\"}*100",
     "legendFormat": "R3 Load 15m"
    },
    {
     "expr": "node_load1{alias=\"relaynode4\"}*100",
     "legendFormat": "R4 Load 1m"
    },
    {
     "expr": "node_load5{alias=\"relaynode3\"}*100",
     "legendFormat": "R4 Load 5m"
    },
    {
     "expr": "node_load15{alias=\"relaynode4\"}*100",
     "legendFormat": "R4 Load 15m"
    }
   ]
  },
  {
   "title": "Time Synchronization (Core Node)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "node_timex_estimated_error_seconds{alias=\"block-producer-node\"}",
     "legendFormat": "Est. error(s)"
    },
    {
     "expr": "node_timex_offset_seconds{alias=\"block-producer-node\"}",
     "legendFormat": "Offset: Node vs. Ref."
    },
    {
     "expr": "node_timex_maxerror_seconds{alias=\"block-producer-node\"}",
     "legendFormat": "Max. Error (s)"
    }
   ]
  },
  {
   "title": "Time Synchronization (Relay1 Node)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "node_timex_estimated_error_seconds{alias=\"relaynode1\"}",
     "legendFormat": "Est. error(s)"
    },
    {
     "expr": "node_timex_offset_seconds{alias=\"relaynode1\"}",
     "legendFormat": "Offset: Node vs. Ref."
    },
    {
     "expr": "node_timex_maxerror_seconds{alias=\"relaynode1\"}",
     "legendFormat": "Max. Error (s)"
    }
   ]
  },
  {
   "title": "Time Synchronization (Relay2 Node)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "node_timex_estimated_error_seconds{alias=\"relaynode2\"}",
     "legendFormat": "Est. error(s)"
    },
    {
     "expr": "node_timex_offset_seconds{alias=\"relaynode2\"}",
     "legendFormat": "Offset: Node vs. Ref."
    },
    {
     "expr": "node_timex_maxerror_seconds{alias=\"relaynode2\"}",
     "legendFormat": "Max. Error (s)"
    }
   ]
  },
  {
   "title": "Block Sync Speed (blocks / min)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate (cardano_node_metrics_blockNum_int{alias=\"block-producer-node\"}[150s]) *60",
     "legendFormat": "Core"
    },
    {
     "expr": "rate (cardano_node_metrics_blockNum_int{alias=\"relaynode1\"}[150s]) *60",
     "legendFormat": "Relay1"
    },
    {
     "expr": "rate (cardano_node_metrics_blockNum_int{alias=\"relaynode2\"}[150s]) *60",
     "legendFormat": "Relay2"
    },
    {
     "expr": "rate (cardano_node_metrics_blockNum_int{alias=\"relaynode3\"}[150s]) *60",
     "legendFormat": "Relay3"
    },
    {
     "expr": "rate (cardano_node_metrics_blockNum_int{alias=\"relaynode4\"}[150s]) *60",
     "legendFormat": "Relay4"
    }
   ]
  },
  {
   "title": "Memory Utilization ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"block-producer-node\"} / (node_memory_MemTotal_bytes{alias=\"block-producer-node\"})))* 100",
     "legendFormat": "Core"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"relaynode1\"} / (node_memory_MemTotal_bytes{alias=\"relaynode1\"})))* 100",
     "legendFormat": "Relay1"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"relaynode2\"} / (node_memory_MemTotal_bytes{alias=\"relaynode2\"})))* 100",
     "legendFormat": "Relay2"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"relaynode3\"} / (node_memory_MemTotal_bytes{alias=\"relaynode3\"})))* 100",
     "legendFormat": "Relay3"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"relaynode4\"} / (node_memory_MemTotal_bytes{alias=\"relaynode4\"})))* 100",
     "legendFormat": "Relay4"
    }
   ]
  },
  {
   "title": "Peak Memory Allocated",
   "type": "graph",
   "description": "Counts only memory that is physically free (from OS, in MBytes)",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "rts_gc_peak_megabytes_allocated{alias=\"block-producer-node\"}",
     "legendFormat": "Core"
    },
    {
     "expr": "rts_gc_peak_megabytes_allocated{alias=\"relaynode1\"}",
     "legendFormat": "Relay1"
    },
    {
     "expr": "rts_gc_peak_megabytes_allocated{alias=\"relaynode2\"}",
     "legendFormat": "Relay2"
    },
    {
     "expr": "rts_gc_peak_megabytes_allocated{alias=\"relaynode3\"}",
     "legendFormat": "Relay3"
    },
    {
     "expr": "rts_gc_peak_megabytes_allocated{alias=\"relaynode4\"}",
     "legendFormat": "Relay4"
    }
   ]
  },
  {
   "title": "Mempool Transactions",
   "type": "graph",
   "description": "current",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "tx" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_txsInMempool_int{alias=\"block-producer-node\"}",
     "legendFormat": "Core"
    },
    {
     "expr": "cardano_node_metrics_txsInMempool_int{alias=\"relaynode1\"}",
     "legendFormat": "Relay2"
    },
    { "legendFormat": "Relay2" },
    {
     "expr": "cardano_node_metrics_txsInMempool_int{alias=\"relaynode3\"}",
     "legendFormat": "Relay3"
    },
    {
     "expr": "cardano_node_metrics_txsInMempool_int{alias=\"relaynode4\"}",
     "legendFormat": "Relay4"
    }
   ]
  },
  {
   "title": "Max \"Residency\"",
   "type": "graph",
   "description": "Amount of live data, MBytes",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "rts_gc_max_bytes_used{alias=\"block-producer-node\"} /(1024*1024)",
     "legendFormat": "Core"
    },
    {
     "expr": "rts_gc_max_bytes_used{alias=\"relaynode1\"} /(1024*1024)",
     "legendFormat": "Relay1"
    },
    {
     "expr": "rts_gc_max_bytes_used{alias=\"relaynode2\"} /(1024*1024)",
     "legendFormat": "Relay2"
    }
   ]
  },
  {
   "title": "Current \"Residency\" (amount of live data)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "rts_gc_current_bytes_used{alias=\"block-producer-node\"}/(1024*1024)",
     "legendFormat": "Core"
    },
    {
     "expr": "rts_gc_current_bytes_used{alias=\"relaynode1\"}/(1024*1024)",
     "legendFormat": "Relay1"
    },
    {
     "expr": "rts_gc_current_bytes_used{alias=\"relaynode2\"}/(1024*1024)",
     "legendFormat": "Relay2"
    },
    {
     "expr": "rts_gc_current_bytes_used{alias=\"relaynode3\"}/(1024*1024)",
     "legendFormat": "Relay3"
    },
    {
     "expr": "rts_gc_current_bytes_used{alias=\"relaynode4\"}/(1024*1024)",
     "legendFormat": "Relay4"
    }
   ]
  },
  {
   "title": "RSS (allocated memory in RAM)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "(cardano_node_metrics_Mem_resident_int{alias=\"block-producer-node\"}*4096)/(1024*1024)",
     "legendFormat": "Core"
    },
    {
     "expr": "(cardano_node_metrics_Mem_resident_int{alias=\"relaynode1\"}*4096)/(1024*1024)",
     "legendFormat": "Relay1"
    },
    {
     "expr": "(cardano_node_metrics_Mem_resident_int{alias=\"relaynode2\"}*4096)/(1024*1024)",
     "legendFormat": "Relay2"
    },
    {
     "expr": "(cardano_node_metrics_Mem_resident_int{alias=\"relaynode3\"}*4096)/(1024*1024)",
     "legendFormat": "Relay3"
    },
    {
     "expr": "(cardano_node_metrics_Mem_resident_int{alias=\"relaynode4\"}*4096)/(1024*1024)",
     "legendFormat": "Relay4"
    }
   ]
  },
  {
   "title": "Aggregate Data Transfer",
   "type": "graph",
   "description": "1 hour rolling window",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias=\"block-producer-node\"}[1h])) * 3600",
     "legendFormat": "Core"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias=\"relaynode1\"}[1h])) * 3600",
     "legendFormat": "Relay1"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias=\"relaynode2\"}[1h])) * 3600",
     "legendFormat": "Relay2"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias=\"relaynode3\"}[1h])) * 3600",
     "legendFormat": "Relay3"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias=\"relaynode4\"}[1h])) * 3600",
     "legendFormat": "Relay4"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{alias=\"block-producer-node\"}",
     "legendFormat": "Core"
    },
    {
     "expr": "node_filefd_allocated{alias=\"relaynode1\"}",
     "legendFormat": "Relay1"
    },
    {
     "expr": "node_filefd_allocated{alias=\"relaynode2\"}",
     "legendFormat": "Relay2"
    },
    {
     "expr": "node_filefd_allocated{alias=\"relaynode3\"}",
     "legendFormat": "Relay3"
    },
    {
     "expr": "node_filefd_allocated{alias=\"relaynode4\"}",
     "legendFormat": "Relay4"
    }
   ]
  }
 ]
}