{
 "title": "SNSKY",
 "description": "SNSKY Pool Monitor",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Activestake",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "target": "pool.livestake", "type": "timeseries" }
   ]
  },
  {
   "title": "Blocks Minted",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "adapools_blocks_lifetime" }
   ]
  },
  {
   "title": "KES Key : Days Left",
   "type": "gauge",
   "description": "Remaining KES DAYS before we need to rotate keys",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(cardano_node_metrics_remainingKESPeriods_int * 1.5)",
     "legendFormat": "{{none}}"
    }
   ]
  },
  {
   "title": "Current Epoch Progress",
   "type": "gauge",
   "description": "Slot height in current epoch (taken from Core node)",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotInEpoch_int{alias=\"block-producer-node\"}/432000 ",
     "legendFormat": "{{none}}"
    }
   ]
  },
  {
   "title": "Epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_epoch_int{alias=\"block-producer-node\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "BP TX's processed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int{alias=\"block-producer-node\"}",
     "legendFormat": "Block Producer"
    },
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int{alias=\"relaynode1\"}",
     "legendFormat": "Relay1"
    },
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int{alias=\"relaynode2\"}",
     "legendFormat": "Relay2"
    }
   ]
  },
  {
   "title": "Peers (Core)",
   "type": "stat",
   "description": "Connected peers to/from Core Node",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_connectedPeers_int{alias=\"block-producer-node\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Pledged",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "adapools_pledged/1000000" }
   ]
  },
  {
   "title": "Blocks Epoch",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "adapools_blocks_epoch" }
   ]
  },
  {
   "title": "Delegators",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "target": "pool.delegators", "type": "timeseries" }
   ]
  },
  {
   "title": "Epoch Leader Slots",
   "type": "stat",
   "description": "Next Epoch",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "snsky_metrics_leaderSlots", "legendFormat": "Leader Slots" }
   ]
  },
  {
   "title": "Core Node System Health",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\",alias=\"block-producer-node\"}[1m])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"block-producer-node\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"block-producer-node\"})",
     "legendFormat": "Disk"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"block-producer-node\"} / (node_memory_MemTotal_bytes{alias=\"block-producer-node\"})))* 100",
     "legendFormat": "RAM"
    },
    {
     "expr": "(1- (node_memory_SwapFree_bytes{alias=\"block-producer-node\"} / node_memory_SwapTotal_bytes{alias=\"block-producer-node\"})) * 100",
     "legendFormat": "SWAP"
    }
   ]
  },
  {
   "title": "Relay Node System Health",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"relaynode1\"} / (node_memory_MemTotal_bytes{alias=\"relaynode1\"})))* 100",
     "legendFormat": "RAM R1"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"relaynode2\"} / (node_memory_MemTotal_bytes{alias=\"relaynode2\"})))* 100",
     "legendFormat": "RAM R2"
    },
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\",alias=\"relaynode1\"}[1m])) * 100)",
     "legendFormat": "CPU R1"
    },
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\",alias=\"relaynode2\"}[1m])) * 100)",
     "legendFormat": "CPU R2"
    },
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\",alias=\"relaynode3\"}[1m])) * 100)",
     "legendFormat": "CPU R3"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Core node uptime",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rts_gc_wall_ms{alias=\"block-producer-node\"} / (1000)",
     "legendFormat": "Core"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Relay node 1 uptime",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rts_gc_wall_ms{alias=\"relaynode1\"} / (1000)",
     "legendFormat": "Relay1"
    },
    {
     "expr": "rts_gc_wall_ms{alias=\"relaynode2\"} / (1000)",
     "legendFormat": "Relay2"
    },
    {
     "expr": "rts_gc_wall_ms{alias=\"relaynode3\"} / (1000)",
     "legendFormat": "Relay3"
    }
   ]
  },
  {
   "title": "Slot Height",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotNum_int{alias=\"block-producer-node\"}",
     "legendFormat": "Core"
    },
    {
     "expr": "cardano_node_metrics_slotNum_int{alias=\"relaynode1\"}",
     "legendFormat": "Relay1"
    },
    {
     "expr": "cardano_node_metrics_slotNum_int{alias=\"relaynode2\"}",
     "legendFormat": "Relay2"
    },
    {
     "expr": "cardano_node_metrics_slotNum_int{alias=\"relaynode3\"}",
     "legendFormat": "Relay3"
    }
   ]
  },
  {
   "title": "Return on Stake",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "target": "pool.roa_total", "type": "timeseries" }
   ]
  },
  {
   "title": "PoolRank",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "target": "pool.ranking", "type": "timeseries" }
   ]
  },
  {
   "title": "Peers (Relay)",
   "type": "stat",
   "description": "Connected peers to/from Relay 1",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_connectedPeers_int{alias=\"relaynode1\"}",
     "legendFormat": "Relay1"
    },
    {
     "expr": "cardano_node_metrics_connectedPeers_int{alias=\"relaynode2\"}",
     "legendFormat": "Relay2"
    },
    {
     "expr": "cardano_node_metrics_connectedPeers_int{alias=\"relaynode3\"}",
     "legendFormat": "Relay3"
    }
   ]
  }
 ]
}